server:
  port: 80
  servlet:
    context-path: /calculator

spring:
  application:
    name: calculator-api
  jackson:
    default-property-inclusion: non_null

management:
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info
      base-path: /

info:
  service:
    name: Calculator API
    description: API for calculation purpouses
    version: @project.version@
    build: @maven.build.timestamp@
